### ISSUE TITLE
autoplay 没有效果

### ISSUE THREAD

**Issue by river42069** [yued-fe/snap-swiper#1]
codesandbox 的 demo里面,
添加了  autoplay: false,
却还是会自动轮播

`snapSwiper({
  imageList,
  el: ".snap-swiper-index",
  autoplay: false
});
`

**Comment by sunseekers** [comment]
> codesandbox 的 demo里面,
> 添加了 autoplay: false,
> 却还是会自动轮播
> 
> `snapSwiper({ imageList, el: ".snap-swiper-index", autoplay: false }); `

代码的bug，现在好了

**Comment by sunseekers** [comment]
🙏

**Comment by sunseekers** [comment]
代码的bug，现在已修复，谢谢了
